"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 30
command_timeout = 3600
add_newline = true

palette = "cyberdream-light"

[character]
success_symbol = "[[󰻠](green) ❯](cyan)"
error_symbol = "[[󰻠](red) ❯](cyan)"
vimcmd_symbol = "[󰻠 ❮](grey)"

[git_branch]
style = "bold magenta"

[directory]
truncation_length = 4
style = "bold cyan"

[palettes.cyberdream-light]
bg = "#ffffff"
bgAlt = "#eaeaea"
bgHighlight = "#acacac"
fg = "#16181a"
grey = "#7b8496"
blue = "#0057d1"
green = "#008b0c"
cyan = "#008c99"
red = "#d11500"
yellow = "#997b00"
magenta = "#d100bf"
pink = "#f40064"
orange = "#d17c00"
purple = "#a018ff"
