# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 30
command_timeout = 3600
add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[ó±žª](fg:iris) \
"""

palette = "rose-pine-dawn"

[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
Documents = "ó°ˆ™"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ âœ“ ](bg:overlay fg:iris)'
untracked = '[?\($count\)](bg:overlay fg:gold)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!\($count\)](bg:overlay fg:gold)'
renamed = '[Â»\($count\)](bg:overlay fg:iris)'
deleted = '[âœ˜\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:gold)'
ahead = '[â‡¡\(${count}\)](bg:overlay fg:foam)'
diverged = 'â‡•[\[](bg:overlay fg:iris)[â‡¡\(${ahead_count}\)](bg:overlay fg:foam)[â‡£\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[â‡£\(${count}\)](bg:overlay fg:rose)'

[time]
disabled = false
format = " [](fg:overlay)[ $time ó°´ˆ ]($style)[](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[](fg:overlay)[ ó°§± $user ]($style)[](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

# Languages
[c]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elixir]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elm]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[haskell]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[java]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[julia]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "ó°Ž™ "

[nim]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "ó°†¥ "

[rust]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[scala]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[python]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = ' '

[conda]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$environment ]($style)[](fg:overlay)"
disabled = false
symbol = 'ðŸ…’ '

# Palette definitions - Rose Pine Dawn
[palettes.rose-pine-dawn]
overlay = '#f2e9e1'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'
